export const metadata = {
  title: 'Terms of Service — CADA Marketing HQ',
}

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px', fontFamily: 'system-ui, sans-serif', color: '#1a1a1a', lineHeight: 1.7 }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ color: '#666', marginBottom: 40 }}>Last updated: July 4, 2026</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>1. Acceptance of Terms</h2>
      <p>By accessing or using CADA Marketing HQ ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>2. Description of Service</h2>
      <p>CADA Marketing HQ is an AI-powered marketing platform that helps businesses create content, plan campaigns, analyse trends, and manage social media publishing.</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>3. Use of Third-Party Platforms</h2>
      <p>The Service integrates with third-party platforms including Instagram, TikTok, and Google. Your use of those platforms is subject to their respective terms of service. We are not responsible for any changes to or interruptions in those platforms.</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>4. User Responsibilities</h2>
      <p>You are responsible for all content you create and publish through the Service. You must not use the Service to post content that violates any applicable laws or the policies of connected platforms.</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>5. Intellectual Property</h2>
      <p>Content generated by the Service using AI models is provided for your use. You retain ownership of any original materials you upload. AI-generated outputs are provided as-is and may not be unique.</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>6. Limitation of Liability</h2>
      <p>The Service is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including any issues with social media publishing or API integrations.</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>7. Modifications</h2>
      <p>We may update these Terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the revised Terms.</p>

      <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 8 }}>8. Contact</h2>
      <p>For questions about these Terms, contact us at <a href="mailto:julia.utomo@gmail.com" style={{ color: '#4f46e5' }}>julia.utomo@gmail.com</a>.</p>
    </div>
  )
}
